server:
  port: 9082

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hrsp_order?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

logging:
  level:
    cn.datawisher.hrsp.order.client.UserFeignClient: debug

#细粒度配置
#feign:
#  client:
#    config:
#      user: # 微服务名称
#        loggerLevel: full

#feign全局配置
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  client:
    config:
      default:
        loggerLevel: full

# actuator 端点全暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'
